name:                Math200Project
version:             0.1.0.0
github:              "edgarlepe/Math200Project"
license:             BSD3
author:              "Edgar Giovanni Lepe"
maintainer:          "lepe.edgar10@gmail.com"
copyright:           "2018 Edgar Giovanni Lepe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/edgarlepe/Math200Project#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Math200Project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Math200Project

tests:
  Math200Project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Math200Project
